CREATE SEQUENCE MedicalIDSeq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

CREATE SEQUENCE PunishmentSeq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

CREATE SEQUENCE Leaveidseq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

  CREATE SEQUENCE TEAMIDSEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

  