-- Insert into COMPANY table
INSERT INTO COMPANY (COMPANYNAME) VALUES ('BHQ');
INSERT INTO COMPANY (COMPANYNAME) VALUES ('HQ');
INSERT INTO COMPANY (COMPANYNAME) VALUES ('OP');
INSERT INTO COMPANY (COMPANYNAME) VALUES ('RR');
INSERT INTO COMPANY (COMPANYNAME) VALUES ('105 BSC');
INSERT INTO COMPANY (COMPANYNAME) VALUES ('203 ABSC');
INSERT INTO COMPANY (COMPANYNAME) VALUES ('124 ABSC');
INSERT INTO COMPANY (COMPANYNAME) VALUES ('EME Sec');

-- Insert into RANKS table
INSERT INTO RANKS (RANK) VALUES ('Lt Col');
INSERT INTO RANKS (RANK) VALUES ('Maj');
INSERT INTO RANKS (RANK) VALUES ('Capt');
INSERT INTO RANKS (RANK) VALUES ('Lt');
INSERT INTO RANKS (RANK) VALUES ('H Lt');
INSERT INTO RANKS (RANK) VALUES ('SWO');
INSERT INTO RANKS (RANK) VALUES ('WO');
INSERT INTO RANKS (RANK) VALUES ('SGT');
INSERT INTO RANKS (RANK) VALUES ('CPL');
INSERT INTO RANKS (RANK) VALUES ('LCPL');
INSERT INTO RANKS (RANK) VALUES ('SNK');
INSERT INTO RANKS (RANK) VALUES ('NC(E)');

-- Insert into TRADE table
INSERT INTO TRADE (TRADE) VALUES ('NA');
INSERT INTO TRADE (TRADE) VALUES ('Y Of S');
INSERT INTO TRADE (TRADE) VALUES ('F Of S');
INSERT INTO TRADE (TRADE) VALUES ('AEC');
INSERT INTO TRADE (TRADE) VALUES ('Clk');
INSERT INTO TRADE (TRADE) VALUES ('OP');
INSERT INTO TRADE (TRADE) VALUES ('SMT');
INSERT INTO TRADE (TRADE) VALUES ('Crypto');
INSERT INTO TRADE (TRADE) VALUES ('D/Sig');
INSERT INTO TRADE (TRADE) VALUES ('W Sig');
INSERT INTO TRADE (TRADE) VALUES ('Tech');
INSERT INTO TRADE (TRADE) VALUES ('E&BR');
INSERT INTO TRADE (TRADE) VALUES ('Cook Unit');
INSERT INTO TRADE (TRADE) VALUES ('Ck Mess');
INSERT INTO TRADE (TRADE) VALUES ('DTMN');
INSERT INTO TRADE (TRADE) VALUES ('C&J');
INSERT INTO TRADE (TRADE) VALUES ('Tbv');
INSERT INTO TRADE (TRADE) VALUES ('Tsa');
INSERT INTO TRADE (TRADE) VALUES ('Wldr');

-- Insert Basic Training Types

INSERT INTO BASICTRAINING (TRGNAME) VALUES ('IPFT');
INSERT INTO BASICTRAINING (TRGNAME) VALUES ('DAY FIRING');
INSERT INTO BASICTRAINING (TRGNAME) VALUES ('NIGHT FIRING');
INSERT INTO BASICTRAINING (TRGNAME) VALUES ('GRENADE FIRING');
INSERT INTO BASICTRAINING (TRGNAME) VALUES ('SPEED MARCH');
INSERT INTO BASICTRAINING (TRGNAME) VALUES ('NIGHT TRAINING');


-- Insert Serving Status 

INSERT INTO SERVINGSTATUS (SERVINGTYPE) VALUES ('Posted');
INSERT INTO SERVINGSTATUS (SERVINGTYPE) VALUES ('Posted Out');
INSERT INTO SERVINGSTATUS (SERVINGTYPE) VALUES ('Retired');
INSERT INTO SERVINGSTATUS (SERVINGTYPE) VALUES ('AWOL');
INSERT INTO SERVINGSTATUS (SERVINGTYPE) VALUES ('Dismissed');
INSERT INTO SERVINGSTATUS (SERVINGTYPE) VALUES ('Deceased');
