-- Trigger for INSERT operation on SOLDIER table
CREATE OR REPLACE TRIGGER soldier_insert_trigger
AFTER INSERT ON SOLDIER
FOR EACH ROW
DECLARE
BEGIN
  INSERT INTO SOLDIERSTATUS (SOLDIER_ID, STATUSID) VALUES (:NEW.SOLDIERID, 1);
END;
/

-- Trigger for DELETE operation on SOLDIER table
CREATE OR REPLACE TRIGGER soldier_delete_trigger
BEFORE DELETE ON SOLDIER
FOR EACH ROW
DECLARE
BEGIN
  DELETE FROM SOLDIERSTATUS WHERE SOLDIER_ID = :OLD.SOLDIERID;
END;
/


INSERT INTO SOLDIERSTATUS (SOLDIER_ID, STATUSID)
SELECT SOLDIERID, 1
FROM SOLDIER;
