CREATE OR REPLACE VIEW OFFICER AS
SELECT
  S.SOLDIERID,
  CONCAT(R.RANK, ' ', S.NAME) AS NAME,
  T.TRADE,
  C.COMPANYNAME,
  E.ERENAME AS ERE_NAME,
  TC.COMDNAME AS TEMP_COMMAND_NAME,
  SS.SERVINGTYPE AS SERVING_STATUS,
  S.MARITALSTATUS,
  S.BLOODGROUP,
  S.WEIGHT,
  S.HEIGHT,
  S.RELIGION,
  S.AGE,
  S.DATEOFBIRTH,
  S.GENDER,
  S.LIVINGSTATUS,
  S.VILLAGE,
  S.THANA,
  S.DISTRICT,
  S.DATEOFENROLL,
  S.ISPRESENT,
FROM SOLDIER S
LEFT JOIN TRADE T ON S.TRADEID = T.TRADEID
LEFT JOIN RANKS R ON S.RANKID = R.RANKID
LEFT JOIN COMPANY C ON S.COMPANYID = C.COMPANYID
LEFT JOIN ERE E ON S.EREID = E.EREID
LEFT JOIN TEMPORARYCOMMAND TC ON S.COMDID = TC.COMDID
LEFT JOIN SERVINGSTATUS SS ON S.STATUSID = SS.STATUSID
WHERE R.RANK IN ('Lt Col', 'Maj', 'Capt', 'Lt', '2Lt');

CREATE OR REPLACE VIEW JCO AS
SELECT
  S.SOLDIERID,
  CONCAT(R.RANK, ' ', S.NAME) AS NAME,
  T.TRADE,
  C.COMPANYNAME,
  E.ERENAME AS ERE_NAME,
  TC.COMDNAME AS TEMP_COMMAND_NAME,
  SS.SERVINGTYPE AS SERVING_STATUS,
  S.MARITALSTATUS,
  S.BLOODGROUP,
  S.WEIGHT,
  S.HEIGHT,
  S.RELIGION,
  S.AGE,
  S.DATEOFBIRTH,
  S.GENDER,
  S.LIVINGSTATUS,
  S.VILLAGE,
  S.THANA,
  S.DISTRICT,
  S.DATEOFENROLL,
  S.ISPRESENT,
FROM SOLDIER S
LEFT JOIN TRADE T ON S.TRADEID = T.TRADEID
LEFT JOIN RANKS R ON S.RANKID = R.RANKID
LEFT JOIN COMPANY C ON S.COMPANYID = C.COMPANYID
LEFT JOIN ERE E ON S.EREID = E.EREID
LEFT JOIN TEMPORARYCOMMAND TC ON S.COMDID = TC.COMDID
LEFT JOIN SERVINGSTATUS SS ON S.STATUSID = SS.STATUSID
WHERE R.RANK IN ('H Lt', 'SWO', 'WO');


CREATE OR REPLACE VIEW otherRanks AS
SELECT
  S.SOLDIERID,
  CONCAT(R.RANK, ' ', S.NAME) AS NAME,
  T.TRADE,
  C.COMPANYNAME,
  E.ERENAME AS ERE_NAME,
  TC.COMDNAME AS TEMP_COMMAND_NAME,
  SS.SERVINGTYPE AS SERVING_STATUS,
  S.MARITALSTATUS,
  S.BLOODGROUP,
  S.WEIGHT,
  S.HEIGHT,
  S.RELIGION,
  S.AGE,
  S.DATEOFBIRTH,
  S.GENDER,
  S.LIVINGSTATUS,
  S.VILLAGE,
  S.THANA,
  S.DISTRICT,
  S.DATEOFENROLL,
  S.ISPRESENT,
FROM SOLDIER S
LEFT JOIN TRADE T ON S.TRADEID = T.TRADEID
LEFT JOIN RANKS R ON S.RANKID = R.RANKID
LEFT JOIN COMPANY C ON S.COMPANYID = C.COMPANYID
LEFT JOIN ERE E ON S.EREID = E.EREID
LEFT JOIN TEMPORARYCOMMAND TC ON S.COMDID = TC.COMDID
LEFT JOIN SERVINGSTATUS SS ON S.STATUSID = SS.STATUSID
WHERE R.RANK IN ('Sgt', 'Cpl', 'Lcpl', 'Snk', 'NCE', 'NCU');
