CREATE OR REPLACE VIEW soldier_view AS
SELECT
  s.SOLDIERID,
  s.NAME,
  s.MARITALSTATUS,
  s.BLOODGROUP,
  s.WEIGHT,
  s.PARENTUNIT,
  s.NOOFCHILDREN,
  s.MISSION,
  s.PERSONALCONTACT,
  s.EMERGENCYCONTACT,
  s.HEIGHT,
  s.RELIGION,
  s.DATEOFBIRTH,
  s.GENDER,
  s.LIVINGSTATUS,
  s.VILLAGE,
  s.THANA,
  s.DISTRICT,
  s.DATEOFENROLL,
  r.RANK,
  t.TRADE,
  c.COMPANYNAME,
  i.PASSPORT_PICTURE_PATH AS PROFILEPICTURE,
  TRUNC(MONTHS_BETWEEN(CURRENT_DATE, s.DATEOFBIRTH) / 12) AS AGE,
  TRUNC(MONTHS_BETWEEN(CURRENT_DATE, s.DATEOFENROLL) / 12) AS SERVICEAGE,
  TRUNC(COALESCE(CURRENT_DATE - l.LEAVEENDDATE, 0)) AS LASTLEAVE
FROM SOLDIER s
LEFT JOIN RANKS r ON s.RANKID = r.RANKID
LEFT JOIN TRADE t ON s.TRADEID = t.TRADEID
LEFT JOIN COMPANY c ON s.COMPANYID = c.COMPANYID
LEFT JOIN (
  SELECT SOLDIERID, MAX(LEAVEENDDATE) AS LEAVEENDDATE
  FROM LEAVEMODULE
  WHERE LEAVEENDDATE <= CURRENT_DATE
  GROUP BY SOLDIERID
) l ON s.SOLDIERID = l.SOLDIERID
LEFT JOIN UPLOADED_IMAGES i ON s.SOLDIERID = i.SOLDIER_ID;
