<?php include '../includes/header.php'; ?>
<div class="card-body">
    <div class="d-flex justify-content-between">
        <div class="text-left">
            <h3>This is a blank page</h3>
        </div>
        <div class="text-right">
        </div>
    </div>
    <!-- Rest of the code -->
</div>

<style>
    .small-table {
        /* Adjust the font size as needed */
        max-width: 100%;
        /* Make the table responsive */
    }
</style>

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Parade State</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="maximize">
                <i class="fas fa-expand"></i>
            </button>
        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table  table-striped table-bordered small-table">
                <tr>
                    <td>DETAILS</td>
                    <td colspan="3">BHQ</td>
                    <td colspan="3">HQ</td>
                    <td colspan="3">RD</td>
                    <td colspan="3">OP</td>
                    <td colspan="3">RR</td>
                    <td colspan="3">203</td>
                    <td colspan="3">124</td>
                    <td colspan="3">EME</td>
                    <td colspan="3">ATTS</td>
                    <td colspan="3">TOTAL</td>

                </tr>
                <tr>
                    <td></td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                    <td>OFFR</td>
                    <td>JCO</td>
                    <td>OR</td>
                </tr>
                <tr>
                    <td>ON PARADE</td>
                    <td>1</td>
                    <td>0</td>
                    <td>7</td>
                    <td>0</td>
                    <td>1</td>
                    <td>13</td>
                    <td>1</td>
                    <td>1</td>
                    <td>12</td>
                    <td>0</td>
                    <td>1</td>
                    <td>2</td>
                    <td>0</td>
                    <td>0</td>
                    <td>5</td>
                    <td>0</td>
                    <td>0</td>
                    <td>1</td>
                    <td>0</td>
                    <td>0</td>
                    <td>9</td>
                    <td>0</td>
                    <td>1</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>7</td>
                    <td>2</td>
                    <td>4</td>
                    <td>56</td>
                </tr>

                <tr>
                    <td>E-TOTAL</td>
                    <td>2</td>
                    <td>0</td>
                    <td>15</td>
                    <td>0</td>
                    <td>0</td>
                    <td>84</td>
                    <td>1</td>
                    <td>1</td>
                    <td>50</td>
                    <td>1</td>
                    <td>2</td>
                    <td>42</td>
                    <td>1</td>
                    <td>3</td>
                    <td>49</td>
                    <td>0</td>
                    <td>1</td>
                    <td>37</td>
                    <td>0</td>
                    <td>2</td>
                    <td>54</td>
                    <td>0</td>
                    <td>0</td>
                    <td>5</td>
                    <td>0</td>
                    <td>0</td>
                    <td>23</td>
                    <td>5</td>
                    <td>9</td>
                    <td>359</td>
                </tr>
                <tr>
                    <td>P-TOTAL</td>
                    <td>3</td>
                    <td>0</td>
                    <td>22</td>
                    <td>0</td>
                    <td>1</td>
                    <td>97</td>
                    <td>2</td>
                    <td>2</td>
                    <td>62</td>
                    <td>1</td>
                    <td>3</td>
                    <td>44</td>
                    <td>1</td>
                    <td>3</td>
                    <td>54</td>
                    <td>0</td>
                    <td>1</td>
                    <td>38</td>
                    <td>0</td>
                    <td>2</td>
                    <td>63</td>
                    <td>0</td>
                    <td>1</td>
                    <td>5</td>
                    <td>0</td>
                    <td>0</td>
                    <td>30</td>
                    <td>7</td>
                    <td>13</td>
                    <td>415</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                </tr>
                <tr>
                    <td>COURSE</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td>2</td>
                    <td>1</td>
                    <td></td>
                    <td>4</td>
                    <td>1</td>
                    <td></td>
                    <td>2</td>
                    <td>1</td>
                    <td></td>
                    <td>11</td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>6</td>
                    <td>0</td>
                    <td>22</td>
                </tr>
                <tr>
                    <td>COMD PERMANENT</td>
                    <td></td>
                    <td>1</td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td></td>
                    <td>4</td>
                    <td></td>
                    <td>1</td>
                    <td>6</td>
                    <td></td>
                    <td>1</td>
                    <td>3</td>
                    <td></td>
                    <td></td>
                    <td>11</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>0</td>
                    <td>3</td>
                    <td>37</td>
                </tr>
                <tr>
                    <td>COMD TEMPORARY</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>6</td>
                    <td></td>
                    <td></td>
                    <td>10</td>
                    <td></td>
                    <td></td>
                    <td>5</td>
                    <td></td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td>11</td>
                    <td></td>
                    <td></td>
                    <td>7</td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>0</td>
                    <td>0</td>
                    <td>42</td>
                </tr>
                <tr>
                    <td>P/L</td>
                    <td></td>
                    <td>1</td>
                    <td>6</td>
                    <td>1</td>
                    <td>2</td>
                    <td>9</td>
                    <td></td>
                    <td></td>
                    <td>13</td>
                    <td></td>
                    <td></td>
                    <td>8</td>
                    <td></td>
                    <td></td>
                    <td>5</td>
                    <td></td>
                    <td></td>
                    <td>2</td>
                    <td>2</td>
                    <td></td>
                    <td>7</td>
                    <td></td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>3</td>
                    <td>3</td>
                    <td>52</td>
                </tr>
                <tr>
                    <td>C/L</td>
                    <td></td>
                    <td>2</td>
                    <td>3</td>
                    <td></td>
                    <td></td>
                    <td>8</td>
                    <td></td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td>5</td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>0</td>
                    <td>2</td>
                    <td>23</td>
                </tr>
                <tr>
                    <td>M/L</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>0</td>
                    <td>0</td>
                    <td>1</td>
                </tr>
                <tr>
                    <td>HOSP</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>3</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>0</td>
                    <td>0</td>
                    <td>3</td>
                </tr>
                <tr>
                    <td>OSL/AWL</td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>0</td>
                    <td>0</td>
                    <td>3</td>
                </tr>
                <tr>
                    <td>A-TOTAL</td>
                    <td>0</td>
                    <td>4</td>
                    <td>11</td>
                    <td>2</td>
                    <td>2</td>
                    <td>35</td>
                    <td>1</td>
                    <td>0</td>
                    <td>35</td>
                    <td>1</td>
                    <td>0</td>
                    <td>21</td>
                    <td>1</td>
                    <td>1</td>
                    <td>26</td>
                    <td>2</td>
                    <td>1</td>
                    <td>18</td>
                    <td>2</td>
                    <td>0</td>
                    <td>32</td>
                    <td>0</td>
                    <td>0</td>
                    <td>5</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>9</td>
                    <td>8</td>
                    <td>183</td>
                </tr>
                <tr>
                    <td>G-TOTAL</td>
                    <td>3</td>
                    <td>4</td>
                    <td>33</td>
                    <td>2</td>
                    <td>3</td>
                    <td>132</td>
                    <td>3</td>
                    <td>2</td>
                    <td>97</td>
                    <td>2</td>
                    <td>3</td>
                    <td>65</td>
                    <td>2</td>
                    <td>4</td>
                    <td>80</td>
                    <td>2</td>
                    <td>2</td>
                    <td>56</td>
                    <td>2</td>
                    <td>2</td>
                    <td>95</td>
                    <td>0</td>
                    <td>1</td>
                    <td>10</td>
                    <td>0</td>
                    <td>0</td>
                    <td>30</td>
                    <td>16</td>
                    <td>21</td>
                    <td>598</td>
                </tr>
            </table>
        </div>
    </div>
</div>

<?php include '../includes/footer.php'; ?>